namespace Misaka.AppEnv
{
    [default_interface]
    static runtimeclass PackageInfo
    {
        static Boolean RunWithId { get; };
        static String InstalledFolder { get; };
        static String LocalFolder { get; };
        static String TemporaryFolder { get; };
    }
}
