namespace Misaka.AppEnv
{
    [default_interface]
    unsealed runtimeclass SettingsBase
    {
        SettingsBase(const String category);
        void ClearValue(const String name);
        void Save();
    }
}
