import "SettingsBase.idl";

namespace Misaka.AppEnv
{
    //[bindable]
    [default_interface]
    runtimeclass SettingsGeneral : SettingsBase
    {
        SettingsGeneral();
        Boolean MinimizeToNotificationArea { get; set; };
        Boolean PushNotification { get; set; };
    }
}
