import "SettingsBase.idl";

namespace Misaka.AppEnv
{
    //[bindable]
    [default_interface]
    runtimeclass SettingsExtractor : SettingsBase
    {
        SettingsExtractor();
        Boolean AutoHook { get; set; };
        Boolean AutoDetach { get; set; };
        String TextractorPath { get; set; };
    }
}
